name: fomc
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.10.0
  - nltk=3.6.5
  - numpy=1.21.2
  - openpyxl=3.0.9
  - pandas=1.3.5
  - pip=21.2.4
  - pyopenssl=22.0.0
  - python=3.9.7
  - regex=2021.11.2
  - requests=2.27.1
  - scipy=1.7.3